bot_controller.py, controllers/checkin.py, requirements.txt, server.py
=> DONE: Feature/checkin

controllers/checkin.py
=> revision error mesage and date

.dockerignore, Dockerfile, README.md, bot_controller.py, controllers/checkin.py, docker-entrypoint.sh, models/user.py, requirements.txt, server.py, tests/test_bot.py
- checkin feature
- deployment refactoring
=> deploy to prod

controllers/checkin.py
Perubahan agar waktu checkin yang disubmit menggunakan utc (tapi yg di display di telegram tetap waktu local)
=> Checkin: Change submission timezone to utc

controllers/checkin.py
1. jika jenis kehadiran bukan wfh,wfo atau perjadin
=> handler message error

docker-compose.yml, models/bot.py
- simplify docker-compose & change start server command to use development server command
- change run_command to use json instead of regular params. this allow more complex telegram feature such as inline & reply keyboard, etc
=> Refactor: change docker-compose & bot.run_command

bot_controller.py, controllers/help.py, models/bot.py
draft implementasi pemecahan command `/help`
Trello: https://trello.com/c/1PsptFhA/259-riset-enhance-help-ada-tampilan-menu-lalu-dibawahnya-muncul-pilihan-help-untuk-melakukan-command-apa-saja-laporan-checkin-whatne
=> feature: split help command

controllers/help.py
Trello: https://trello.com/c/1PsptFhA/259-riset-enhance-help-ada-tampilan-menu-lalu-dibawahnya-muncul-pilihan-help-untuk-melakukan-command-apa-saja-laporan-checkin-whatne
=> Help command: add items & change keyboard layout

models/bot.py, models/groupware.py
Agar pesan error ke pengguna di telegram lebih jelas & singkat
=> Telegram & Groupware API: change connection error message

controllers/cekabsensi.py, models/groupware.py, models/user.py
Ubah sumber list peserta dari awalnya pakai hasil `user.get_user()` (yang sumbernya dari list alias di database) menjadi endpoint `/user` di api groupware.
List alias itu isinya tidak update (tidak mencerminkan kalau ada karyawan baru atau yg sudah resign). Daftar yang paling update ada di endpoint `/user`
=> Cekabsensi: update user list source 'user' endpoint

controllers/help.py, controllers/setalias.py, models/user.py
perubahan help sedikit, dan buat agar kalau username belum ada di list alias, akan insert new, bukan return not found
=> Setalias: update help & allow adding new user alias

.codeclimate.yml
=> codeclimate (setup-for-python):

models/groupware.py
=> Cekabsensi: fix holiday integration

models/groupware.py
difficultyTask is now ignored on digiteam API
=> Lapor: set difficultyTask to empty on send

models/bot.py, models/groupware.py
clickup card: https://app.clickup.com/t/6bqy3d
=> Lapor: set isMainTask to empty on send

controllers/help.py
Clickup card: https://app.clickup.com/t/6bucmk
=> Help: fix message for `checkin` & `setalias` command

controllers/healthcheck.py, models/db.py, models/groupware.py, server.py
Clickup card: https://app.clickup.com/t/6kw81u
pengembangan ini berguna untuk menambah informasi di status.digitalservice.id
=> Healthcheck: add endpoint to check telegram, db, dan groupware connection

controllers/cekabsensi.py
Card clickup: https://app.clickup.com/t/6bucn4
=> Cekabsensi: create custom message if everyone present

controllers/cekabsensi.py, controllers/help.py, models/user.py
add feature to filter cekabsensi list by divisi name
clickup card: https://app.clickup.com/t/77ttx2
=> Cekabsensi: add filter by divisi

controllers/cekabsensi.py, controllers/help.py, controllers/main.py, models/user.py
- add `/cekabsensi` filter option
- update `/whatsnew` & `/help` command accordingly
=> Deploy to production

controllers/main.py, controllers/ulangtahun.py, models/user.py, server.py, tests/controllers/test_ulangtahun.py
bentuknya berupa command `/ulangtahun` serta endpoint `/ulangtahun` (untuk dipanggil dari luar dengan cron)
=> Add 'ulangtahun' feature

controllers/ulangtahun.py, server.py
- when accessed via telegam command, send fixed message when list empty
- when triggered via endpoint (for scheduler use) no msg is sent when list empty
=> Deploy command /ulangtahun changes regarding behaviour on list empty

controllers/ulangtahun.py, server.py
card trello: https://app.clickup.com/t/a819dk
=> deploy to master: perbaikan cek hari libur untuk endpoint `/cekabsensi`

example.env, models/groupware.py, tests/controllers/test_main.py, tests/models/test_groupware.py
This changes allow for more granular control over which debug info should be printed
=> Change IS_DEBUG env var into VERBOSITY_LEVEL

README.md, example.env, models/groupware.py, tests/controllers/test_main.py, tests/models/test_groupware.py
=> deploy to prod: Change IS_DEBUG env var into VERBOSITY_LEVEL

controllers/checkin.py
Currently if use custom date, would use predefined hour & minute
=> Added capability to checkin command to input custom date

controllers/checkin.py
project: Digiteam
title: limit checkin before 7:30
participants: @robyjuliansyah @sandisunandar99 
screenshot: https://user-images.githubusercontent.com/8702575/217481921-e1c821cc-08cf-43e1-aa6d-afd4ce89baec.png
=> limit checkin before 7:30

models/groupware.py
- title: adjust: use difficultyTask when creating evidence on bot Digiteam
- project: Digiteam
- participants: @ayocodingit @azophy @feriahmad
=> adjust: use difficultyTask when create evidence on bot digiteam
